### ISSUE TITLE
Add tile for downloading the app onto mobile/tablet home screen

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#1]
When I download the web-app, 
I want to be able to use it on my smartphone or tablet 
Since I don't really use laptops or PCs.

### Acceptance Criteria
- [x] Can be downloaded as a 'tile' to put on smartphone/tablet home screen
- [x] Pages can be displayed for a smartphone screen and a tablet screen

Mobile-first, Web-second

![a logo](https://user-images.githubusercontent.com/43782867/47004766-2c7cad00-d12a-11e8-9413-0e743d92a0b6.png)

**Comment by SimonLab** [comment]
@tiffany-tang the favicons have been added and the icon is now displayed when you add the app 
![image](https://user-images.githubusercontent.com/6057298/47913447-0e39df80-de94-11e8-9010-36448f561d91.png)

**Comment by tiffany-tang** [comment]
👍
