### ISSUE TITLE
Post-dev bug fixing

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#103]
- how do we inform you guys on the adjustments? Is it on here?
- how long do we anticipate the adjustments will be address, as you might have different clients by then?

**Comment by tiffany-tang** [comment]
@iteles @Cleop 
I have a couple of additional questions:
- How many hours constitutes as "half-day"? It's actually easier for us to understand the hourly timeframe rather than by day if that makes sense.
- Can we split that "half-day" over a few days? We're wondering if during our MVP testing between 19th - 26th we came across any emergency bug situation we can immediately flag it up with you guys. 

Thank you!

**Comment by iteles** [comment]
This was answered prior to @tiffany-tang's departure:
+ Opening issue on github is the way to inform us of changes
+ We will liaise with you at the time on availability for adjustments to be made - this will depend on their priority as described in the SLAs
+ Contractually, a full day is 7 hours (half a day being 3.5) and we can split this across multiple days no problem 😊 As we discussed, we may just have to play a little with our availability at the time as well as the urgency of the request.

Thanks!

**Comment by tiffany-tang** [comment]
Hi Ines,
Kate here - can only get Tiffany's log in to work! Thanks for flagging up I should be using Github for new/additional requests.

The ask I currently have is:

•	To include an error message pop-up, if the log-in or PIN details are entered incorrectly. Highest priority. 
•	To remove the option to enter more than 1 character in each PIN space – feedback was that this was happening on tablets (sorry I haven’t got a screencap but are you able to check this?)
•	To remove case sensitivity in usernames (no idea how easy this is?!)

Thanks for the info on cost - do you have an idea of how long these fixes would take, and when you could fit it in?

**Comment by iteles** [comment]
@tiffany-tang (Kate!) We're on it in terms of estimating 👍 
Ideally, for future issues, it would be great to have them opened as separate issues so we can keep one thing to fix per issue for historical tracking 😊 

Will get back to you on this later today.

**Comment by tiffany-tang** [comment]
Sorry! Will do in future!

**Comment by tiffany-tang** [comment]
Checked on iPhone 7 and Samsung Galaxy and fixes working - thank you for being so speedy!
