### ISSUE TITLE
Forbidden message again!

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#104]
I just kept the app opened on my samsung phone, then I used my iphone to log into another account. When I return to the samsung phone to log out, the Forbidden message is shown. 

It's slightly worrying that this is consistently happening to an android phone.

**Comment by SimonLab** [comment]
I have deployed the application a few minutes ago (which might have reset the cookies session). This might be the source of the forbidden message.

Otherwise did you use the same user at the same time to log on your phones?

**Comment by tiffany-tang** [comment]
I think it was the deployment, because I deliberately used different accounts.

**Comment by SimonLab** [comment]
@tiffany-tang I'm going to deploy the application soon to update the small content changes. It's possible you'll see this forbidden message
