### ISSUE TITLE
Content change - Something else reflect 

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#105]
Is it possible to take out the sentence "Sometimes it's hard to know what is it that you're feeling"

<img src="https://user-images.githubusercontent.com/43782867/47914490-cddc6080-de97-11e8-8080-6f8d5c6aa31c.jpg" width=200px />

**Comment by SimonLab** [comment]
@tiffany-tang do you want this change only on the "something else" emtion or also on the "I don't know" emotion:
![image](https://user-images.githubusercontent.com/6057298/47915032-7ccd6c00-de99-11e8-89b1-8bd634309c91.png)

**Comment by tiffany-tang** [comment]
Thanks, looks good!
