### ISSUE TITLE
Upgrade heroku plan?

### ISSUE THREAD

**Issue by SimonLab** [actnforchildren/mental_health_app#107]
At the moment the application is deployed on the free plan on Heroku. This is a good option while developing but I would recommend to upgrade to the next plan (7$ a month) at least for this month while the users are using the application (you could downgrade the plan when the application is not used if necessary)

![image](https://user-images.githubusercontent.com/6057298/47998272-a20ae600-e0f6-11e8-8831-e45078abbb60.png)

The main point of having the 7$ plan is to have the application constantly running and to not wait for the application to "wake up" (this takes a couple of minutes but it can be annoying for users if they want to use the application quickly)

@tiffany-tang let me know you thought :+1:

**Comment by tiffany-tang** [comment]
@SimonLab I will need to ask the relevant higher ups about this. Thanks for letting us know :)

**Comment by tiffany-tang** [comment]
@SimonLab I was wondering whether you can tell me more about this. Say if we want to upgrade the plan, who do we contact about this? Similarly, if we want to downgrade the plan, what is the procedure for that and who do we contact?

**Comment by SimonLab** [comment]
@tiffany-tang the upgrade/downgrade is done on the Heroku settings. If you have the credentials you should be able to connect to the dashboard.
Then a couple of clicks you will be able to update the "dyno plan":
![image](https://user-images.githubusercontent.com/6057298/48360079-51ffc680-e696-11e8-86b1-4abbf1a20572.png)

![image](https://user-images.githubusercontent.com/6057298/48360091-5a580180-e696-11e8-9542-46602bc7dd6f.png)

@iteles @Cleop do you know how we manage this process on our other projects?

**Comment by tiffany-tang** [comment]
@SimonLab  @iteles @Cleop 
I currently still haven't had the credentials to heroku nor the Redash account.

**Comment by tiffany-tang** [comment]
@SimonLab @iteles @Cleop 
Just had a chat about this with Rachael, if you can forward the heroku log in details to us that will be great! Thank you!

**Comment by iteles** [comment]
@tiffany-tang We're on it!

**Comment by tiffany-tang** [comment]
@iteles I'll send you an email about this since this repo is public

**Comment by iteles** [comment]
@tiffany-tang I have both transferred ownership of the heroku app to the email you sent me and shared the credentials document.

**Comment by tiffany-tang** [comment]
@iteles thanks for letting me know - I will forward this to the person looking after the email and let you know how it went down
