### ISSUE TITLE
App usage location

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#109]
Hey just want to clarify that none of you are in Puerto Rico right now? 

I just had a look at GA and it's saying someone's using it in Puerto Rico... so I'm just curious who might be using it there since no one in my team are there.

**Comment by SimonLab** [comment]
I think the team is in UK/Portugal at the moment.
Do you know how many visits do you have from there? It might also be a bot/crawler

**Comment by tiffany-tang** [comment]
One for now. There's also a couple from Ireland and that's about it for the anomalies.
