### ISSUE TITLE
Coping strategies accordion UX issue

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#111]
This is more of a UX issue where it will provide better UX if the accordian can automatically close if users open another accordion. 

With this in mind, it might be better approach to solve the issue for measuring click event for the accordion - discussed in #56

**Comment by iteles** [comment]
@tiffany-tang We can make the first change requested (the accordion closes if another one is opened) but the click events will involve some additional work in term of complex analytics (this isn't done through Redash) which hasn't been set up yet.

**Comment by tiffany-tang** [comment]
@iteles  Re click events - when I discussed this with @Cleop we have agreed this will be put in the backlog so not expecting this to happen at this stage

**Comment by tiffany-tang** [comment]
@SimonLab The accordion seems fine so far, however, when I click the accordion below the current one I have opened, it jumped to the middle of the next accordion.

Shown here:
<img src="https://user-images.githubusercontent.com/43782867/48423024-bafb4300-e757-11e8-9c45-a1bf561f5b68.jpeg" width=200px />

Scrolled down to click on Try being mindful
<img src="https://user-images.githubusercontent.com/43782867/48423051-ca7a8c00-e757-11e8-96e1-54c55d0ec329.jpg" width=200px />

After I clicked on Try being mindful
<img src="https://user-images.githubusercontent.com/43782867/48423116-e7af5a80-e757-11e8-8bfd-528042af690d.jpg" width=200px />

**Comment by tiffany-tang** [comment]
Thanks, looks good to me :)
