### ISSUE TITLE
Safari bug - keyboard issues when entering PIN

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#112]
Previously discussed on #5 and closed, but if this can be addressed will be great.

The issue is when entering the PIN on safari, the keyboard's default view will be the alphabets and hence when typing the PIN, users will have to consistently change to the number-symbols view for each slot.

**Comment by SimonLab** [comment]
At the moment we are using the type "password" for the pin inputs. unfortunately there is not a way to limit the password type to be just number.
```<input type="password" name="" value="">```

We can achieve this by using a type "number" on the input but the password will not be hidden anymore automatically. We can use a css rule to hide the number like on the password but this solution only work for Opera, Chrome and Safari:
`-webkit-text-security: disc;`

I would suggest we try to this solution and have some feedback while testing.

**Comment by tiffany-tang** [comment]
Looks good to me! Thanks!
