### ISSUE TITLE
Emails not being sent for MVP testing accounts

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#114]
These accounts are the ones for the MVP testing mentioned #64 

This wasn't mentioned in Kate's email, but we just found out these accounts are not sending emails to the trusted adult account. On the app, it will indicate the email has been sent. 

The previous testing accounts (test_user, test1-9) are working just fine in terms of this function.

**Comment by SimonLab** [comment]
Sorry for that, the emails were sent to the wrong trusted adult email. The database has been updated and this should be fixed now.

**Comment by tiffany-tang** [comment]
@SimonLab tested with iphone, samsung phone, ipad. All good.
