### ISSUE TITLE
Hotjar

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#126]
Hi guys,

Kate here - Tiffany is off sick today. I have been speaking to Ines and she's agreed that you will be able to add a Hotjar code, snipped to each page of the app. We will do the rest of the analytics set up internally. 

Code below, needs adding to the <head> tag on every page I believe.

Please can this be completed as a matter of urgency today?

Thanks,

Kate

```
<!-- Hotjar Tracking Code for http://actnforchildren.herokuapp.com -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:1089602,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

```

**Comment by SimonLab** [comment]
The Hotjar script has been added to the application:
![image](https://user-images.githubusercontent.com/6057298/48551551-c1133000-e8cd-11e8-9905-86bf0518982b.png)

@tiffany-tang does it work on your side?

**Comment by tiffany-tang** [comment]
All good
