### ISSUE TITLE
Block test accounts

### ISSUE THREAD

**Issue by afcdigital** [actnforchildren/mental_health_app#130]
Hi guys,
Please could you freeze/block the accounts that were set up for user testing as we are now at the end of the prototype test and I don't want the children to still be able to log in if we're not monitoring their responses.
Thanks,
Kate

**Comment by afcdigital** [comment]
@iteles @Cleop sorry having trouble with this new account so can't assign anybody to this request

**Comment by iteles** [comment]
@afcdigital I've only just seen this, apologies! We're on it.

It looks like there's a pending invitation to give you the correct permissions for this repo as well, just go to: https://github.com/actnforchildren/mental_health_app/invitations 😊

**Comment by SimonLab** [comment]
@afcdigital I'm looking at this now :+1: 
It should be easy and quick to remove access to the accounts for the kids. However do you want to create a permission system where admins from AFC can still login into these accounts (this will take longer to implement, ~1/2 day)?

**Comment by afcdigital** [comment]
Hi @SimonLab - sorry for the delay in responding. If access was simply revoked for those usernames, would there ever be a way to reinstate them or would they be 'lost forever'?

**Comment by iteles** [comment]
@afcdigital Do you have a preference?

**Comment by afcdigital** [comment]
Let's do with that - reject any login preference.
Sorry for the delay @iteles @SimonLab

**Comment by afcdigital** [comment]
Thanks!

**Comment by afcdigital** [comment]
Sorry when I said that I wanted the prototype test accounts blocking, I meant the ones with animal names. Not the ones we're using internally for testing: 
test_user     1234
test1         1111
test2         2222
test3         3333
test4         4444
test5         5555
test6         6666
test7         7777
test8         8888
test9         9999

Can these be reinstated? We use these to show potential funders the product!

**Comment by afcdigital** [comment]
I've just found out that we have a meeting this afternoon with MPs (now, in fact!!) and would be great to have these accounts open for testing? Is this possible @SimonLab? Or at least 1 account open now, and the rest open for another funder meeting tomorrow?

**Comment by iteles** [comment]
@afcdigital Simon had already put in some time this morning so we were able to review, merge and deploy! Should be up and ready  for you to test before the MPs see it 😊

**Comment by afcdigital** [comment]
All working! Thank you SO much and sorry for the confusion before!
