### ISSUE TITLE
Mid-November MVP testing need for analytics

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#14]
Analytics/metrics we’ll want to measure:
- How often do YP log in? e.g. everyday, multiple times a day
  - This assumes they have to re-log in every time they use the app? If this isn't the case, can we measure how many times they open it whilst logged in
- How often do YP use a coping strategy?
  - Which were most popular?
- How often do YP use the emotions log?
- What emotions are YP clicking on?
- What reasons are they giving for their emotions?
- How often do YP click I don't know?
- How do YP describe how they're feeling when they cannot identify the emotion?
- How often do YP click other?
- What other emotions are YP feeling? [other]
- How often do YP view the calendar?
- How often do YP switch the calendar view and to what?
- How often do YP share how they feel with their trusted adult?
- How often do YP access the help screen?
- How often do YP access the coping toolbox from the navigation?
 
Why measure these:
- To gather quantitative evidence that the product is liked/in use
- To gather qualitative feedback on user journey (what users look to access when, and in what order), future content (e.g. the physical symptoms logic requirement, what other emotions should be added), and future dev requirements (e.g. are weekly/monthly calendars even needed, how should coping strategies be accessed in the future)
 
In addition to the above, we’ll be gathering qualitative feedback each day of the test, and will conduct interviews at the end of the week – but these won’t impact analytical requirements.

**Comment by Cleop** [comment]
The relevant issues were created and Google Analytics was implemented for the primary requirements. Then Redash was also added for more detailed analytics.
