### ISSUE TITLE
App usability testing - 24th Oct (Wednesday)

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#32]
Usability testing will be on 24th Oct, which will likely happen between 4 - 6pm.

We will be testing with 6 young people on the day and so we will need 8 test username and PIN. Usernames can simply be named test1, 2, 3, 4, 5, 6, 7, 8.

**Comment by Cleop** [comment]
@tiffany-tang - can this issue now be closed?
