### ISSUE TITLE
Calendar Weekly View

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#36]
When I am tracking my logged emotions using the calendar, 
I would like to see how I have been doing throughout the week,
So I can identify how I have been generally feeling for the past week. 

### Acceptance criteria
- [x] Weekly view will be a list view showing the total number of logs for each emotions
- [x] "Week" will be shown as the last 7 days including today
- [x] Contain a button that allow users to send this information to a trusted adult (does not need to be able to send to Trusted adult at this stage - refer to #13 )

The wording will be: '8 times in 7 days' rather than '8 of 7 days'

![image](https://user-images.githubusercontent.com/16775804/47424876-9b888000-d780-11e8-94dc-42398ce79ccf.png)

**Comment by SimonLab** [comment]
@tiffany-tang sorry I wasn't sure if you wanted the button with "Contain a button that allow users to send this information to a trusted adult (does not need to be able to send to Trusted adult at this stage - refer to #13 )"

I'll add it to the page :+1:

**Comment by tiffany-tang** [comment]
@SimonLab Hey I just accidentally closed that issue a couple days ago. If there's time we can tackle that otherwise I will make this a new issue and close this one.

**Comment by tiffany-tang** [comment]
@SimonLab similar to #37

**Comment by tiffany-tang** [comment]
Email received - for the content of the email, I might put it in the backlog for future references :)
