### ISSUE TITLE
Calendar Monthly View

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#37]
When I have been using the web-app for a month,
I would like to look back at my progress,
So I can see how my emotions have improved/changed through out the month.

### Acceptance criteria
- [x] Monthly view will be a bar chart showing the total number of logs for each emotions - refer to reply in #36 
- [x] Month will be shown as a month in the year (ie January, February)
- [x] Contain a button that allow users to send this information to a trusted adult (does not need to be able to send to Trusted adult at this stage - refer to #13 )

**Comment by tiffany-tang** [comment]
@SimonLab Sorry keep on accidentally closing this issue - is this still awaiting review?

**Comment by SimonLab** [comment]
This is ready for testing, I'll update the issue label :+1:

**Comment by tiffany-tang** [comment]
Thanks! All good :)
