### ISSUE TITLE
Calendar UI enhancement

### ISSUE THREAD

**Issue by SimonLab** [actnforchildren/mental_health_app#50]
On mobile the calendar is open/close with the current selected text:
![image](https://user-images.githubusercontent.com/6057298/47367458-99b6b200-d6d7-11e8-84b3-eae425892c2a.png)
- Instead of this element being a "p" tag we can change this to a button
- It can be difficult to change the month, I'm wondering if a swipe event on the calendar would make it easier

**Comment by SimonLab** [comment]
the swipe event listener has been added to the other view (weekly/monthly)

**Comment by tiffany-tang** [comment]
@SimonLab looks good!
