### ISSUE TITLE
Implement more complex analytics

### ISSUE THREAD

**Issue by Cleop** [actnforchildren/mental_health_app#56]
Issue #55 is for the implementation of GA. However there are a number of other more complex metrics which @tiffany-tang would like to measure. There are a couple of ways these could be measured either with Redash or with Google Tag Manager. The original scope did not include analytics beyond what GA can offer 'out of the box', however if time allows these measures would be useful:

- [ ] # clicks on the coping toolbox on the navigation
- [ ] # clicks on a coping strategy title (think about closing the strategy)
- [ ] # clicks on the dropdown calender icon
- [ ] # clicks on the toolbox button to open the toolbox modal
- [ ] # clicks on daily, weekly, monthly (lower priority)
- [ ] Funnel for which pages people go to from calendar view (lower priority)

### Redash
- [x] # time each emotion was selected (Redash)
- [x] # clicks on 'YES' for sharing with a trusted adult (Redash)
- [x] # of daily logs (over the course of a week) (Redash)
- [x] What reasons are they giving for their emotions? (Redash)
- [x] How do YP describe how they're feeling when they cannot identify the emotion? (Redash)
- [x] What other emotions are YP feeling? [other] (Redash)

**Comment by tiffany-tang** [comment]
@Cleop Is this something we can try setting up on our own on GA?

**Comment by Cleop** [comment]
Hey @tiffany-tang - I split out the analytics issues into 2. The first (#55) being things you can do yourself once the initial script is in (as it now is). 

This issue and the points in it are things that require developer input. This was just me doing a cursory glance over the points from my memory of GA vs Google Tag Manager/ Redash. So if you do find that you can get any of these bullet points in Google Analytics then that's great but my guess is that you won't be able to.

**Comment by tiffany-tang** [comment]
@Cleop I'm still slightly confused so I'll try to write this out with what I understood and please tell me where I got wrong. 

So essentially #55 is what is already included in GA from the get-go. If we want to measure any of the above, we will need to either find a way to do it ourselves in GA, or if you have the time you will do that for us?

**Comment by Cleop** [comment]
Correct re #55 which is for Google Analytics

With what is included in this issue, it will need either Google Tag Manager and/or Redash. Both of these need some developer work on the app so you as a PO won't be able to set this up. However, another developer at AFC could, but what I'm trying to say is that it's a 'technical' task. 

So yes, if we have time we will do as much of this as we can 👍  

I hope that helps, we can always clarify things on stand up tomorrow 😊

**Comment by tiffany-tang** [comment]
@Cleop I remember when we had this discussion a few months back Ines did mention Redash as a possibility. That's when I assumed it will be part of the scope. 

Is it possible to prioritise this as GA will not be able to give us much meaningful data to justify further development?

**Comment by tiffany-tang** [comment]
@Cleop @iteles I just had a catch-up with Sherry who attended all the meetings prior to dev - she noted that during those meetings, in addition to GA, Google Tag Manager was also agreed to be part of the scope. 

It is really important for us to be able to get the analytics sorted out as the data will be a crucial part when we present to stakeholders for future stages.

**Comment by Cleop** [comment]
@tiffany-tang - I've reviewed our progress and been through this issue with @SimonLab. I've updated the top comment to reflect which of the requirements can be met using Redash. With the time we have left we are confident that we will be able to implement Redash which covers the 6/12 of the points above.

Redash and Google Analytics should provide ample data for analysis as they are platforms that provide vast amounts of flexibility and functionality without the need for editing code on the project.

Google Tag Manager behaves slightly differently. Technically we have already 'implemented' it as we've added the Tag Manager script. But, despite the script being 'connected' until you define specific tags via the data layer it doesn't provide any 'out of the box' functionality. A developer has to edit the data layer in the code to do this. In principle you could create an infinite number of tags in the data layer and therefore unless you create a predetermined list, you can't guarantee how long it will take and therefore if it will be feasible. I'd be more than happy to talk through how this works in more detail on stand up tomorrow :blush:

**Comment by Cleop** [comment]
Following our stand up this morning we have agreed that @SimonLab is going to dedicate his remaining time (aside from the tasks we discussed on standup) to analytics in whichever way @tiffany-tang prefers. We discussed the advantages and disadvantages of the different analytics platforms and how they're implemented and how long that takes.

So now @tiffany-tang is going to update us once she's had a chance to weigh up the pros and cons of each as well as the specific goals/needs of the project to let us know exactly how she would like @SimonLab to use that time.

For your reference @tiffany-tang, some of those options were:

**Redash**
- Read only: @SimonLab will need to spend his time writing the queries you want as you won't be able to write queries yourself. But the advantage of read only is you don't need to learn how to write queries and there's no danger of you accidentally altering the live database.
- Write access: less work for @SimonLab as you can write queries yourself however we should give you a demo of how to write a query and then you also need to learn a little SQL. You should also be mindful of not deleting or editing the live data.

**Tag Manager**
- It seems like this won't give us as much useful data at this stage compared to Redash given that each tag needs to be individually created by a developer and it can't give us access to the data people are entering in the same way as Redash.

@tiffany-tang will investigate whether Redash subscription can be granted for free from Redash by messaging them or whether AfC would like to pay the $49 for the basic monthly subscription. Alternatively we can simply use the 1 month free trial (which began being used from yesterday) which would cover the November testing period and therefore be sufficient at this stage.

**Comment by Cleop** [comment]
@tiffany-tang - how have you been getting along? Have you made any decisions yet?

**Comment by tiffany-tang** [comment]
@Cleop @SimonLab 
Had a thought about what we can measure and where we can look at the data. I have re-juggled some for Redash and some for GA, but I might need your opinion whether some of the ones 

**Redash**
- # of times each emotion is logged 
- What are the emotions users report when they log Something Else
- What reasons do they give for feeling a certain emotion (from the checkbox + say it yourself box)
- # of clicks on Yes to send email to trusted adult
- # of clicks on No to not send email to trusted adult
- How many times in the week did users log their emotions
- # of clicks on the calendar icon
- # of clicks on the dates on the calendar

**Google analytics**
- How many times users are logging or relogging in per day?
- How often are they viewing their previous entries?
- How often do they view the weekly and monthly calendar views?
- How often do they access the More Info page?
- How often do users access the Help page?
- How often do users access the Toolbox from the navigation?

**Comment by tiffany-tang** [comment]
@Cleop @SimonLab I have forgotten to add in my last comment - if possible I will would like to have read-only access to Redash

**Comment by Cleop** [comment]
Just a couple of notes based on your comment on Redash for us to discuss on our stand up tomorrow:
**Redash**
- no of times each emotion is logged 
- What are the emotions users report when they log Something Else
- What reasons do they give for feeling a certain emotion (from the checkbox + say it yourself box)
- no of times users send email to trusted adult
(- no of clicks on No to not send email to trusted adult - can be inferred from point above?)
- How many times in the week did users log their emotions (# of emotions logged/ users/ time)

**Can't be done on Redash:**

- no of clicks on the calendar icon
- no of clicks on the dates on the calendar

**Comment by tiffany-tang** [comment]
@Cleop sounds good to me!

**Comment by Cleop** [comment]
@tiffany-tang - here is a repo we have made to help you learn about Redash and how to write queries:
https://github.com/dwyl/learn-redash

You want to read from the title: **'An introduction to SQL for writing queries'**

**Comment by tiffany-tang** [comment]
> Just a couple of notes based on your comment on Redash for us to discuss on our stand up tomorrow:
> 
> **Redash**
> 
> * no of times each emotion is logged
> * What are the emotions users report when they log Something Else
> * What reasons do they give for feeling a certain emotion (from the checkbox + say it yourself box)
> * no of times users send email to trusted adult
>   (- no of clicks on No to not send email to trusted adult - can be inferred from point above?)
> * How many times in the week did users log their emotions (# of emotions logged/ users/ time)
> 
> **Can't be done on Redash:**
> 
> * no of clicks on the calendar icon
> * no of clicks on the dates on the calendar

@SimonLab for your reference

**Comment by tiffany-tang** [comment]
@Cleop @SimonLab Quick question - am I currently on Read-only access or Write access? Because I'm seeing the error message "Error running query: You do not have permission to run queries with this data source." for number of logs per emotions, say it yourself, no of emotions logged per user, and whenever I tried to refresh each query to get the latest data.

**Comment by SimonLab** [comment]
You are with Read-only acces but it might be more restrictive than I thought
![image](https://user-images.githubusercontent.com/6057298/48061867-35582000-e1b8-11e8-82e6-cc14149be6e3.png)

I've switch your user to the default group, try again to refresh/run some queries to see if it fixes the issue.
