### ISSUE TITLE
Accounts for final testing in November

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#64]
We have received confirmation for the last testing location for our last testing, and also the final number of children participating.

- We will need 35 accounts set up for that
- The usernames will be a combination of an animal and a 2 digit number

E.g. Username: weasel19     PIN: 2333

[MVP testing usernames.xlsx](https://github.com/actnforchildren/mental_health_app/files/2534453/MVP.testing.usernames.xlsx)

Update from 31/10: The document has since been updated as we now require 35 accounts instead of 30.

**Comment by tiffany-tang** [comment]
@SimonLab Will I be able to test all these today or tomorrow?

**Comment by SimonLab** [comment]
@tiffany-tang depending how fast I finish the other changes/issues I might be able to update the database tonight otherwise it will be ready for tomorrow morning.

Concerning the current data (test1, test2...) do you want to keep them or is it ok if we reset the database?

**Comment by tiffany-tang** [comment]
@SimonLab Cool no worries. Just checking :)

Re current data, why is it you want to reset the database? I have no issues either way I'm just curious.

**Comment by SimonLab** [comment]
When the structure of the database changed a lot during the development, it's sometimes easier to rebuild the database (which can implies to reset the data). But I think we should be able to just add the new accounts

**Comment by tiffany-tang** [comment]
No worries - if you feel there's a need to reset the database go for it!

**Comment by SimonLab** [comment]
@tiffany-tang I've just created the new users. Let me know if it's working on your side :+1:

**Comment by SimonLab** [comment]
@tiffany-tang I just fixed the typo :+1:

**Comment by tiffany-tang** [comment]
@SimonLab tested! everything is good 👍
