### ISSUE TITLE
Coping toolbox modals 

### ISSUE THREAD

**Issue by RobStallion** [actnforchildren/mental_health_app#70]
As a user, when I am logging a negative emotion 
I want to be able to click on a toolbox button and see coping strategies that could help me

- [x] A modal will pop up for users to see the Coping Toolbox when they are in the 'Negative' Reflect pages.

**Comment by tiffany-tang** [comment]
@RobStallion Opening and closing the modal itself is fine. However, when I tried to open the concertinas, I find it very difficult to read everything from the most bottom one. If I open all the concertinas, I couldn't even scroll to the last one.

**Comment by RobStallion** [comment]
Hey @tiffany-tang Good spot 🔍. There was an issue with safari styling this element. Adding fix now. Will re-add the please test label when it has been deployed. 

Thanks

**Comment by tiffany-tang** [comment]
Everything is fine :) Closed.
