### ISSUE TITLE
Content for Angry coping strategy

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#81]
There are 4 coping strategies for Angry
- Spot your warning signs
- Controlled Breathing
- Burn off that energy
- Write how you feel

In the attached document, the name of the coping strategy is in bold, and the steps are the paragraphs underneath it. 

[Coping strategies for ANGER FINAL.docx](https://github.com/actnforchildren/mental_health_app/files/2534348/Coping.strategies.for.ANGER.FINAL.docx)

**Comment by tiffany-tang** [comment]
Bullet points 1, 2, 3 should end with a question mark - please change. 

Otherwise all good :)

**Comment by SimonLab** [comment]
This should be now ready to be tested @tiffany-tang

**Comment by tiffany-tang** [comment]
Looks good :)
