### ISSUE TITLE
Redash account

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#95]
@Cleop Just in case AfC might want to pay the subscription for Redash, will you be passing the account details over to us?

**Comment by Cleop** [comment]
@tiffany-tang - yes we can do of course. @SimonLab - which email did you use to set up Redash, the gmail account or your dwyl account?

**Comment by SimonLab** [comment]
@Cleop I've created the redash account with the gmail account created specifically for the project. We'll share with you all the credentials you'll need to manage the application

**Comment by Cleop** [comment]
@tiffany-tang - @iteles will be sharing the credentials doc with you via email. But you should now have access to Redash so please feel free to close this issue if you have successfully logged in to your Redash.
