### ISSUE TITLE
BUG - PIN turning from number to asterisks during input

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#97]
@SimonLab Sorry to add more to your plate - so I addressed this with @RobStallion earlier that the asterisks are turning really slowly in Safari. But it seems for Google Chrome, it's not turning into the asterisks at all.

**Comment by SimonLab** [comment]
@tiffany-tang I've just tested on my phone and on my desktop with chrome and unfortunately I can't reproduce the error.
Do you have more information about device and maybe the chrome version you have tested the app?

**Comment by tiffany-tang** [comment]
@SimonLab I have just gave it a try as well, it's fine now.
