### ISSUE TITLE
Something else - daily log page and email

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#99]
As discussed earlier, Something else is still not showing the inputted emotion (e.g. Silly) on the daily log page. 

I tried experimenting with the email and it also show "else" instead of "silly (e.g.)".

**Comment by SimonLab** [comment]
The feeling is now displayed instead of the emotion name for "Something else"

**Comment by tiffany-tang** [comment]
Everything is good 👍
